name: CI

on:
  push:
    branches:
      - main
      - ci-*
  pull_request:
    branches:
      - main

jobs:
  nix-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Use Nix cache
        uses: DeterminateSystems/magic-nix-cache-action@v4

      - name: Run nix flake check for writer-assistant
        run: cd writer-assistant && nix flake check
